apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata: {name: nccl-test-dra}
spec:
  slotsPerWorker: 1
  runPolicy: {cleanPodPolicy: Running}
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          tolerations: [{key: sku, value: gpu, operator: Equal, effect: NoSchedule}]
          containers:
          - name: nccl
            image: ghcr.io/coreweave/nccl-tests:12.9.1-devel-ubuntu24.04-nccl2.29.2-1-d73ec07
            command: ["/bin/bash","-c"]
            args:
            - |
              sleep 15
              mpirun -np 2 --allow-run-as-root -bind-to none -mca routed direct -mca oob_tcp_if_include eth0 -mca btl_tcp_if_include eth0 -mca plm_rsh_no_tree_spawn 1 -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_DEBUG_SUBSYS=INIT,NET -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_IB_DISABLE=0 -x NCCL_SHM_DISABLE=1 -x NCCL_MNNVL_ENABLE=0 -x NCCL_NVLS_ENABLE=0 -x NCCL_NET_GDR_LEVEL=SYS -x NCCL_IB_HCA=mlx5 /opt/nccl_tests/build/all_reduce_perf -b 512M -e 4G -f 2 -g 1 -c 0
    Worker:
      replicas: 2
      template:
        spec:
          tolerations:
          - {key: sku, value: gpu, operator: Equal, effect: NoSchedule}
          - {key: nvidia.com/gpu, operator: Exists, effect: NoSchedule}
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector: {matchLabels: {training.kubeflow.org/job-name: nccl-test-dra, training.kubeflow.org/job-role: worker}}
                topologyKey: kubernetes.io/hostname
          automountServiceAccountToken: false
          resourceClaims:
          - {name: gpu-nic-aligned, resourceClaimTemplateName: gpu-nic-aligned}
          containers:
          - name: nccl
            image: ghcr.io/coreweave/nccl-tests:12.9.1-devel-ubuntu24.04-nccl2.29.2-1-d73ec07
            resources:
              claims:
              - {name: gpu-nic-aligned}
            securityContext: {privileged: true}
